#include "sndpch.h"
#include "SandboxEngine/Core/Input.h"
#include <GLFW/glfw3.h>

void snd::InitInputMaps()
{
    memset(gButtonMap, INVALID_INDEX, sizeof(gButtonMap));
    memset(gAxisMap, INVALID_INDEX, sizeof(gAxisMap));

    // Printable keys
    gButtonMap[INPUT_KEY_SPACE]         = GLFW_KEY_SPACE;
    gButtonMap[INPUT_KEY_APOSTROPHE]    = GLFW_KEY_APOSTROPHE;
    gButtonMap[INPUT_KEY_COMMA]         = GLFW_KEY_COMMA;
    gButtonMap[INPUT_KEY_MINUS]         = GLFW_KEY_MINUS;
    gButtonMap[INPUT_KEY_PERIOD]        = GLFW_KEY_PERIOD;
    gButtonMap[INPUT_KEY_SLASH]         = GLFW_KEY_SLASH;
    gButtonMap[INPUT_KEY_0]             = GLFW_KEY_0;
    gButtonMap[INPUT_KEY_1]             = GLFW_KEY_1;
    gButtonMap[INPUT_KEY_2]             = GLFW_KEY_2;
    gButtonMap[INPUT_KEY_3]             = GLFW_KEY_3;
    gButtonMap[INPUT_KEY_4]             = GLFW_KEY_4;
    gButtonMap[INPUT_KEY_5]             = GLFW_KEY_5;
    gButtonMap[INPUT_KEY_6]             = GLFW_KEY_6;
    gButtonMap[INPUT_KEY_7]             = GLFW_KEY_7;
    gButtonMap[INPUT_KEY_8]             = GLFW_KEY_8;
    gButtonMap[INPUT_KEY_9]             = GLFW_KEY_9;
    gButtonMap[INPUT_KEY_SEMICOLON]     = GLFW_KEY_SEMICOLON;
    gButtonMap[INPUT_KEY_EQUAL]         = GLFW_KEY_EQUAL;
    gButtonMap[INPUT_KEY_A]             = GLFW_KEY_A;
    gButtonMap[INPUT_KEY_B]             = GLFW_KEY_B;
    gButtonMap[INPUT_KEY_C]             = GLFW_KEY_C;
    gButtonMap[INPUT_KEY_D]             = GLFW_KEY_D;
    gButtonMap[INPUT_KEY_E]             = GLFW_KEY_E;
    gButtonMap[INPUT_KEY_F]             = GLFW_KEY_F;
    gButtonMap[INPUT_KEY_G]             = GLFW_KEY_G;
    gButtonMap[INPUT_KEY_H]             = GLFW_KEY_H;
    gButtonMap[INPUT_KEY_I]             = GLFW_KEY_I;
    gButtonMap[INPUT_KEY_J]             = GLFW_KEY_J;
    gButtonMap[INPUT_KEY_K]             = GLFW_KEY_K;
    gButtonMap[INPUT_KEY_L]             = GLFW_KEY_L;
    gButtonMap[INPUT_KEY_M]             = GLFW_KEY_M;
    gButtonMap[INPUT_KEY_N]             = GLFW_KEY_N;
    gButtonMap[INPUT_KEY_O]             = GLFW_KEY_O;
    gButtonMap[INPUT_KEY_P]             = GLFW_KEY_P;
    gButtonMap[INPUT_KEY_Q]             = GLFW_KEY_Q;
    gButtonMap[INPUT_KEY_R]             = GLFW_KEY_R;
    gButtonMap[INPUT_KEY_S]             = GLFW_KEY_S;
    gButtonMap[INPUT_KEY_T]             = GLFW_KEY_T;
    gButtonMap[INPUT_KEY_U]             = GLFW_KEY_U;
    gButtonMap[INPUT_KEY_V]             = GLFW_KEY_V;
    gButtonMap[INPUT_KEY_W]             = GLFW_KEY_W;
    gButtonMap[INPUT_KEY_X]             = GLFW_KEY_X;
    gButtonMap[INPUT_KEY_Y]             = GLFW_KEY_Y;
    gButtonMap[INPUT_KEY_Z]             = GLFW_KEY_Z;
    gButtonMap[INPUT_KEY_LEFT_BRACKET]  = GLFW_KEY_LEFT_BRACKET;
    gButtonMap[INPUT_KEY_BACKSLASH]     = GLFW_KEY_BACKSLASH;
    gButtonMap[INPUT_KEY_RIGHT_BRACKET] = GLFW_KEY_RIGHT_BRACKET;
    gButtonMap[INPUT_KEY_GRAVE_ACCENT]  = GLFW_KEY_GRAVE_ACCENT;

    // Function keys.
    gButtonMap[INPUT_KEY_ESCAPE]        = GLFW_KEY_ESCAPE;
    gButtonMap[INPUT_KEY_ENTER]         = GLFW_KEY_ENTER;
    gButtonMap[INPUT_KEY_TAB]           = GLFW_KEY_TAB;
    gButtonMap[INPUT_KEY_BACKSPACE]     = GLFW_KEY_BACKSPACE;
    gButtonMap[INPUT_KEY_INSERT]        = GLFW_KEY_INSERT;
    gButtonMap[INPUT_KEY_DELETE]        = GLFW_KEY_DELETE;
    gButtonMap[INPUT_KEY_RIGHT]         = GLFW_KEY_RIGHT;
    gButtonMap[INPUT_KEY_LEFT]          = GLFW_KEY_LEFT;
    gButtonMap[INPUT_KEY_DOWN]          = GLFW_KEY_DOWN;
    gButtonMap[INPUT_KEY_UP]            = GLFW_KEY_UP;
    gButtonMap[INPUT_KEY_PAGE_UP]       = GLFW_KEY_PAGE_UP;
    gButtonMap[INPUT_KEY_PAGE_DOWN]     = GLFW_KEY_PAGE_DOWN;
    gButtonMap[INPUT_KEY_HOME]          = GLFW_KEY_HOME;
    gButtonMap[INPUT_KEY_END]           = GLFW_KEY_END;
    gButtonMap[INPUT_KEY_CAPS_LOCK]     = GLFW_KEY_CAPS_LOCK;
    gButtonMap[INPUT_KEY_SCROLL_LOCK]   = GLFW_KEY_SCROLL_LOCK;
    gButtonMap[INPUT_KEY_NUM_LOCK]      = GLFW_KEY_NUM_LOCK;
    gButtonMap[INPUT_KEY_PRINT_SCREEN]  = GLFW_KEY_PRINT_SCREEN;
    gButtonMap[INPUT_KEY_PAUSE]         = GLFW_KEY_PAUSE;
    gButtonMap[INPUT_KEY_F1]            = GLFW_KEY_F1;
    gButtonMap[INPUT_KEY_F2]            = GLFW_KEY_F2;
    gButtonMap[INPUT_KEY_F3]            = GLFW_KEY_F3;
    gButtonMap[INPUT_KEY_F4]            = GLFW_KEY_F4;
    gButtonMap[INPUT_KEY_F5]            = GLFW_KEY_F5;
    gButtonMap[INPUT_KEY_F6]            = GLFW_KEY_F6;
    gButtonMap[INPUT_KEY_F7]            = GLFW_KEY_F7;
    gButtonMap[INPUT_KEY_F8]            = GLFW_KEY_F8;
    gButtonMap[INPUT_KEY_F9]            = GLFW_KEY_F9;
    gButtonMap[INPUT_KEY_F10]           = GLFW_KEY_F10;
    gButtonMap[INPUT_KEY_F11]           = GLFW_KEY_F11;
    gButtonMap[INPUT_KEY_F12]           = GLFW_KEY_F12;
    gButtonMap[INPUT_KEY_F13]           = GLFW_KEY_F13;
    gButtonMap[INPUT_KEY_F14]           = GLFW_KEY_F14;
    gButtonMap[INPUT_KEY_F15]           = GLFW_KEY_F15;
    gButtonMap[INPUT_KEY_F16]           = GLFW_KEY_F16;
    gButtonMap[INPUT_KEY_F17]           = GLFW_KEY_F17;
    gButtonMap[INPUT_KEY_F18]           = GLFW_KEY_F18;
    gButtonMap[INPUT_KEY_F19]           = GLFW_KEY_F19;
    gButtonMap[INPUT_KEY_F20]           = GLFW_KEY_F20;
    gButtonMap[INPUT_KEY_F21]           = GLFW_KEY_F21;
    gButtonMap[INPUT_KEY_F22]           = GLFW_KEY_F22;
    gButtonMap[INPUT_KEY_F23]           = GLFW_KEY_F23;
    gButtonMap[INPUT_KEY_F24]           = GLFW_KEY_F24;
    gButtonMap[INPUT_KEY_F25]           = GLFW_KEY_F25;
    gButtonMap[INPUT_KEY_KP_0]          = GLFW_KEY_KP_0;
    gButtonMap[INPUT_KEY_KP_1]          = GLFW_KEY_KP_1;
    gButtonMap[INPUT_KEY_KP_2]          = GLFW_KEY_KP_2;
    gButtonMap[INPUT_KEY_KP_3]          = GLFW_KEY_KP_3;
    gButtonMap[INPUT_KEY_KP_4]          = GLFW_KEY_KP_4;
    gButtonMap[INPUT_KEY_KP_5]          = GLFW_KEY_KP_5;
    gButtonMap[INPUT_KEY_KP_6]          = GLFW_KEY_KP_6;
    gButtonMap[INPUT_KEY_KP_7]          = GLFW_KEY_KP_7;
    gButtonMap[INPUT_KEY_KP_8]          = GLFW_KEY_KP_8;
    gButtonMap[INPUT_KEY_KP_9]          = GLFW_KEY_KP_9;
    gButtonMap[INPUT_KEY_KP_DECIMAL]    = GLFW_KEY_KP_DECIMAL;
    gButtonMap[INPUT_KEY_KP_DIVIDE]     = GLFW_KEY_KP_DIVIDE;
    gButtonMap[INPUT_KEY_KP_MULTIPLY]   = GLFW_KEY_KP_MULTIPLY;
    gButtonMap[INPUT_KEY_KP_SUBTRACT]   = GLFW_KEY_KP_SUBTRACT;
    gButtonMap[INPUT_KEY_KP_ADD]        = GLFW_KEY_KP_ADD;
    gButtonMap[INPUT_KEY_KP_ENTER]      = GLFW_KEY_KP_ENTER;
    gButtonMap[INPUT_KEY_KP_EQUAL]      = GLFW_KEY_KP_EQUAL;
    gButtonMap[INPUT_KEY_LEFT_SHIFT]    = GLFW_KEY_LEFT_SHIFT;
    gButtonMap[INPUT_KEY_LEFT_CTRL]     = GLFW_KEY_LEFT_CONTROL;
    gButtonMap[INPUT_KEY_LEFT_ALT]      = GLFW_KEY_LEFT_ALT;
    gButtonMap[INPUT_KEY_LEFT_SUPER]    = GLFW_KEY_LEFT_SUPER;
    gButtonMap[INPUT_KEY_RIGHT_SHIFT]   = GLFW_KEY_RIGHT_SHIFT;
    gButtonMap[INPUT_KEY_RIGHT_CTRL]    = GLFW_KEY_RIGHT_CONTROL;
    gButtonMap[INPUT_KEY_RIGHT_ALT]     = GLFW_KEY_RIGHT_ALT;
    gButtonMap[INPUT_KEY_RIGHT_SUPER]   = GLFW_KEY_RIGHT_SUPER;
    gButtonMap[INPUT_KEY_MENU]          = GLFW_KEY_MENU;

    // Mouse buttons.
    gButtonMap[INPUT_MOUSE_LEFT]    = GLFW_MOUSE_BUTTON_LEFT;
    gButtonMap[INPUT_MOUSE_RIGHT]   = GLFW_MOUSE_BUTTON_RIGHT;
    gButtonMap[INPUT_MOUSE_MIDDLE]  = GLFW_MOUSE_BUTTON_MIDDLE;

    // Gamepad buttons.
    gButtonMap[INPUT_GAMEPAD_FACE_UP]       = GLFW_GAMEPAD_BUTTON_Y;
    gButtonMap[INPUT_GAMEPAD_FACE_RIGHT]    = GLFW_GAMEPAD_BUTTON_B;
    gButtonMap[INPUT_GAMEPAD_FACE_DOWN]     = GLFW_GAMEPAD_BUTTON_A;
    gButtonMap[INPUT_GAMEPAD_FACE_LEFT]     = GLFW_GAMEPAD_BUTTON_X;
    gButtonMap[INPUT_GAMEPAD_LB]            = GLFW_GAMEPAD_BUTTON_LEFT_BUMPER;
    gButtonMap[INPUT_GAMEPAD_RB]            = GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER;
    gButtonMap[INPUT_GAMEPAD_BACK]          = GLFW_GAMEPAD_BUTTON_BACK;
    gButtonMap[INPUT_GAMEPAD_START]         = GLFW_GAMEPAD_BUTTON_START;
    gButtonMap[INPUT_GAMEPAD_GUIDE]         = GLFW_GAMEPAD_BUTTON_GUIDE;
    gButtonMap[INPUT_GAMEPAD_LTHUMB]        = GLFW_GAMEPAD_BUTTON_LEFT_THUMB;
    gButtonMap[INPUT_GAMEPAD_RTHUMB]        = GLFW_GAMEPAD_BUTTON_RIGHT_THUMB;
    gButtonMap[INPUT_GAMEPAD_DPAD_UP]       = GLFW_GAMEPAD_BUTTON_DPAD_UP;
    gButtonMap[INPUT_GAMEPAD_DPAD_RIGHT]    = GLFW_GAMEPAD_BUTTON_DPAD_RIGHT;
    gButtonMap[INPUT_GAMEPAD_DPAD_DOWN]     = GLFW_GAMEPAD_BUTTON_DPAD_DOWN;
    gButtonMap[INPUT_GAMEPAD_DPAD_LEFT]     = GLFW_GAMEPAD_BUTTON_DPAD_LEFT;

    // Mouse axes.
    // GLFW provides cursor position as separate function,
    // no delta cursor postion and callback for scroll.

    // Gamepad axes.
    gAxisMap[INPUT_GAMEPAD_LX]  = GLFW_GAMEPAD_AXIS_LEFT_X;
    gAxisMap[INPUT_GAMEPAD_LY]  = GLFW_GAMEPAD_AXIS_LEFT_Y;
    gAxisMap[INPUT_GAMEPAD_RX]  = GLFW_GAMEPAD_AXIS_RIGHT_X;
    gAxisMap[INPUT_GAMEPAD_RY]  = GLFW_GAMEPAD_AXIS_RIGHT_Y;
    gAxisMap[INPUT_GAMEPAD_LT]  = GLFW_GAMEPAD_AXIS_LEFT_TRIGGER;
    gAxisMap[INPUT_GAMEPAD_RT]  = GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER;
}
